project:
  type: website

website:
  title: "Automata"
  description: Notes on technology
  favicon: assets/logo.svg
  site-url: "https://jeev20.github.io"
  navbar:
    background: dark
    right:
      - text: "About"
        href: about.qmd
  page-footer:
    center:
      - text: "Made with {{< quarto >}}uarto"
        href: "https://quarto.org"
  
  
  
      
format:
  html:
    theme:
      dark: [cosmo, theme-dark.scss]
      light: cosmo
    css: styles.css
    include-in-header: 
      - text: |
          <script data-goatcounter="https://86633.goatcounter.com/count" 
          async src="//gc.zgo.at/count.js"></script>
    code-line-numbers: false
    code-overflow: wrap
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem



logo: assets/logo.svg

typography:
  fonts:
    - family: Montserrat
      source: google
  base: Montserrat
  headings: Montserrat


extensions:
  iconify:
    set: "octicon"
    width: "1.2em"
    height: "1.2em"
    flip: "horizontal"
    rotate: "0deg"
    inline: true
    mode: "svg"
