project:
  type: website

website:
  title: "Automata"
  favicon: assets/logo.svg
  navbar:
    right:
      - about.qmd
      - text: "Resume"
        href: assets/resume.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/jeevhegde
  page-footer:
    center:
      - text: "Written in Quarto!"
        href: "https://quarto.org"
  
      
format:
  html:
    theme:
      dark: darkly
      light: simplex
    css: styles.css
    include-in-header: 
      - text: |
          <script data-goatcounter="https://86633.goatcounter.com/count" 
          async src="//gc.zgo.at/count.js"></script>
    code-line-numbers: false
    code-overflow: wrap

logo: assets/logo.svg

typography:
  fonts:
    - family: Montserrat
      source: google
  base: Montserrat
  headings: Montserrat


