project:
  type: website

website:
  title: "Automata"
  favicon: assets/logo.svg
  navbar:
    right:
      - text: About
        href: about.qmd
  page-footer:
    center:
      - text: "Made with Quarto {{< quarto >}}"
        href: "https://quarto.org"
  
      
format:
  html:
    theme:
      dark: darkly
      light: simplex
    css: styles.css
    include-in-header: 
      - text: |
          <script data-goatcounter="https://86633.goatcounter.com/count" 
          async src="//gc.zgo.at/count.js"></script>
    code-line-numbers: false
    code-overflow: wrap

logo: assets/logo.svg

typography:
  fonts:
    - family: Montserrat
      source: google
  base: Montserrat
  headings: Montserrat


extensions:
  iconify:
    set: "octicon"
    width: "1.2em"
    height: "1.2em"
    flip: "horizontal"
    rotate: "0deg"
    inline: true
    mode: "svg"
