---
title: Bruno API client
description: "A local and git friendly API client"
author: "Jeevith Hegde"
format: html
toc: true
lang: en
jupyter: python3
ipynb-shell-interactivity: all
execute:
  echo: false
date: 2024-06-02
categories: ["api client"]
tags: [ "api testing", "integration"]
comments:
  giscus:
    repo: jeev20/jeev20.github.io
---

I recently opened up Postman to access an old collection. To my surprise, Postman has now fully gone the cloud way and syncs all collections to the cloud. 

This means that if I somehow forgot to remove my tokens or credentials, they can potential be synced to Postman servers!

The scratchpad within Postman is also limited now and is next to useless. I did also try insomnia, and it seems they too have fallen for the same honeypot!

There has to be a better API client, and my search today ended with bruno.

## [bruno](https://www.usebruno.com) 
A great alternative to postman or insomnia. 

bruno is written in electron the same framework used by Visual Studio Code and the code is open-source with a MIT license.  

The founders [manifesto](https://www.usebruno.com/manifesto) is a treat to read for any open-source enthusiast. 

Bruno is offered both as a free version and a paid version.


The paid version cost `$19` for 2 machines for a span of 2 years. After which the renewal is set to 60% of the `$19` to cover development of the project. The feature set is great for my use-case and I admire Anoop's honesty. I bought the Golden Edition (Individual License) today (2.6.2024)

::: {.callout}

I wish bruno and Anoop great success. It is so refreshing to see when a great product meets a transparent and simple founder. 

::: 

Here are some YouTube videos to get started with bruno.

{{< video https://www.youtube.com/embed/R3F6Gu7tG8M >}}

{{< video https://www.youtube.com/embed/7bSMFpbcPiY >}}

